# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChangeName.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'ChangeName.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43hangeName.proto\x12\x05proto\"9\n\x13\x43SModifyNicknameReq\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\x10\n\x08use_card\x18\x02 \x01(\x08\"\'\n\x13\x43SModifyNicknameRes\x12\x10\n\x08nickname\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChangeName_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSMODIFYNICKNAMEREQ']._serialized_start=27
  _globals['_CSMODIFYNICKNAMEREQ']._serialized_end=84
  _globals['_CSMODIFYNICKNAMERES']._serialized_start=86
  _globals['_CSMODIFYNICKNAMERES']._serialized_end=125
# @@protoc_insertion_point(module_scope)
