# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CreateGuild.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'CreateGuild.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43reateGuild.proto\"\xca\x01\n\x12\x43reateGuildRequest\x12\x11\n\tGuildName\x18\x01 \x01(\t\x12\x0e\n\x06Slogan\x18\x04 \x01(\t\x12\x13\n\x0bPaymentType\x18\x05 \x01(\x05\x12\x14\n\x0c\x41utoApproval\x18\x06 \x01(\x05\x12\x10\n\x08Location\x18\x07 \x01(\x05\x12\x10\n\x08MinLevel\x18\t \x01(\x05\x12\x11\n\tMinBrRank\x18\n \x01(\x05\x12\x0e\n\x06\x41vatar\x18\x0b \x01(\x05\x12\x11\n\tMinCsRank\x18\x0c \x01(\x05\x12\x0c\n\x04Tags\x18\r \x03(\x05\"&\n\x13\x43reateGuildResponse\x12\x0f\n\x07GuildId\x18\x01 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CreateGuild_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEGUILDREQUEST']._serialized_start=22
  _globals['_CREATEGUILDREQUEST']._serialized_end=224
  _globals['_CREATEGUILDRESPONSE']._serialized_start=226
  _globals['_CREATEGUILDRESPONSE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
